DESIGN_NAME: ctu_can
VERILOG_FILES:
  - dir::../../verilog/rtl/ahbl_1/apb_0/ctu_can/ctu_can.v

PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc
CLOCK_PORT: clk_sys
CLOCK_PERIOD: 15
SYNTH_STRATEGY: DELAY 0
CLOCK_UNCERTAINTY_CONSTRAINT: 0.2
MAX_TRANSITION_CONSTRAINT: 1
MAX_FANOUT_CONSTRAINT: 16
TIME_DERATING_CONSTRAINT: 6.5
SYNTH_EXCLUDED_CELL_FILE: dir::no_synth.cells

FP_SIZING: absolute
DIE_AREA: [0, 0, 580, 580]
FP_PIN_ORDER_CFG: dir::pin_order.cfg

FP_PDN_MULTILAYER: false
FP_PDN_HSPACING: 10
FP_PDN_HPITCH: 80
FP_PDN_VPITCH: 80
FP_PDN_HOFFSET: 5

DIODE_ON_PORTS: both
PL_WIRE_LENGTH_COEF: 0.1
PL_TARGET_DENSITY_PCT: 59
PL_RESIZER_ALLOW_SETUP_VIOS: true
CTS_SINK_CLUSTERING_SIZE: 40
CTS_SINK_CLUSTERING_MAX_DIAMETER: 120
CTS_CLK_MAX_WIRE_LENGTH: 800

DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
DESIGN_REPAIR_MAX_SLEW_PCT: 30
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 30
GRT_ADJUSTMENT: 0.05
GRT_ALLOW_CONGESTION: true
RT_MAX_LAYER: met4

RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
RUN_HEURISTIC_DIODE_INSERTION: true
HEURISTIC_ANTENNA_THRESHOLD: 250
MAGIC_DEF_LABELS: false
