DESIGN_NAME: EF_QSPI_XIP_CTRL_AHBL
VERILOG_FILES:
  - dir::../../ip/EF_QSPI_XIP_CTRL/hdl/rtl//DMC.v
  - dir::../../ip/EF_QSPI_XIP_CTRL/hdl/rtl/EF_QSPI_XIP_CTRL.v
  - dir::../../ip/EF_QSPI_XIP_CTRL/hdl/rtl/bus_wrappers/EF_QSPI_XIP_CTRL_AHBL.v
VERILOG_DEFINES: 
  - PnR
  - USE_POWER_PINS

PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc
CLOCK_PORT: HCLK
CLOCK_PERIOD: 15
SYNTH_STRATEGY: DELAY 0
CLOCK_UNCERTAINTY_CONSTRAINT: 0.15
MAX_TRANSITION_CONSTRAINT: 1
MAX_FANOUT_CONSTRAINT: 16
TIME_DERATING_CONSTRAINT: 6.5
SYNTH_EXCLUDED_CELL_FILE: dir::no_synth.cells
EXTRA_EXCLUDED_CELLS: 
  - sky130_fd_sc_hd__nand4_1
  - sky130_fd_sc_hd__nand3_1

FP_SIZING: absolute
DIE_AREA: [0, 0, 800, 500]
FP_PIN_ORDER_CFG: dir::pin_order.cfg

FP_PDN_MULTILAYER: false
FP_PDN_HSPACING: 10
FP_PDN_HPITCH: 80
FP_PDN_VPITCH: 80
FP_PDN_HOFFSET: 5

DIODE_ON_PORTS: both
DIODE_PADDING: 0
PL_WIRE_LENGTH_COEF: 0.1
PL_TARGET_DENSITY_PCT: 60
PL_TIME_DRIVEN: false
PL_RESIZER_ALLOW_SETUP_VIOS: true
CTS_SINK_CLUSTERING_SIZE: 40
CTS_SINK_CLUSTERING_MAX_DIAMETER: 120
CTS_CLK_MAX_WIRE_LENGTH: 800

DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
DESIGN_REPAIR_MAX_SLEW_PCT: 30
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 30
GRT_ADJUSTMENT: 0.1
GRT_ALLOW_CONGESTION: true
RT_MAX_LAYER: met4

RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
RUN_HEURISTIC_DIODE_INSERTION: true
HEURISTIC_ANTENNA_THRESHOLD: 160
MAGIC_DEF_LABELS: false

# skip yosys synthesis checks as it fails due rst_din input ports to FLASH_RESET that's not used in the RTL
ERROR_ON_SYNTH_CHECKS: false