DESIGN_NAME: usb_cdc_wrapper_ahbl
VERILOG_FILES:
  - dir::../../ip/usb_cdc/hdl/rtl/bulk_endp.v
  - dir::../../ip/usb_cdc/hdl/rtl/ctrl_endp.v
  - dir::../../ip/usb_cdc/hdl/rtl/in_fifo.v
  - dir::../../ip/usb_cdc/hdl/rtl/out_fifo.v
  - dir::../../ip/usb_cdc/hdl/rtl/phy_rx.v
  - dir::../../ip/usb_cdc/hdl/rtl/phy_tx.v
  - dir::../../ip/usb_cdc/hdl/rtl/sie.v
  - dir::../../ip/usb_cdc/hdl/rtl/usb_cdc.v
  - dir::../../ip/usb_cdc_wrapper/hdl/rtl/usb_cdc_wrapper.v
  - dir::../../ip/usb_cdc_wrapper/hdl/rtl/bus_wrappers/usb_cdc_wrapper_ahbl.pp.v

PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc
CLOCK_PORT: HCLK
CLOCK_PERIOD: 40
SYNTH_STRATEGY: AREA 1
CLOCK_UNCERTAINTY_CONSTRAINT: 0.15
MAX_TRANSITION_CONSTRAINT: 1
MAX_FANOUT_CONSTRAINT: 16
TIME_DERATING_CONSTRAINT: 8.0

FP_SIZING: absolute
DIE_AREA: [0, 0, 350, 230]
FP_ASPECT_RATIO: 1
FP_PIN_ORDER_CFG: dir::pin_order.cfg

FP_PDN_MULTILAYER: false
FP_PDN_VWIDTH: 1.6
FP_PDN_HSPACING: 10
FP_PDN_HPITCH: 80
FP_PDN_VPITCH: 80
FP_PDN_HOFFSET: 5

DIODE_ON_PORTS: both
PL_WIRE_LENGTH_COEF: 0.1
PL_TARGET_DENSITY_PCT: 70
PL_RESIZER_ALLOW_SETUP_VIOS: true
CTS_SINK_CLUSTERING_SIZE: 40
CTS_SINK_CLUSTERING_MAX_DIAMETER: 120
CTS_CLK_MAX_WIRE_LENGTH: 800

DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 500
DESIGN_REPAIR_MAX_SLEW_PCT: 30
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 30
GRT_ADJUSTMENT: 0.12
GRT_ALLOW_CONGESTION: true
RT_MAX_LAYER: met4

RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
RUN_HEURISTIC_DIODE_INSERTION: true
HEURISTIC_ANTENNA_THRESHOLD: 160
MAGIC_DEF_LABELS: false
